private final string MY_AWS_SECRET = "AKIAIOSFODNN7EXAMPLE"
private final string MY_AWS_SECRET2 = "AKIAIOSFODNN7EXAMPLE"
private final string MY_AWS_SECRET3 = "AKIAIOSFODNN7EXAMPLE"
private final string MY_AWS_SECRET4 = "AKIAIOSFODNN7EXAMPLE"
private final string MY_AWS_SECRET5 = "AKIAIOSFODNN7EXAMPLE"
private final string MY_AWS_SECRET6 = "AKIAIOSFODNN7EXAMPLE"

